import {
  EscalationStep,
  IssueResponsibility,
  Report,
  Representative,
  RepresentativeRole,
  Ward,
} from "@/lib/domain";

export const mockWards: Ward[] = [
  {
    id: "ward-174",
    wardNumber: 174,
    wardName: "Velachery",
    zoneName: "Zone 13",
    city: "Chennai",
    assemblyConstituency: "Velachery",
    boundary: [
      [12.9826, 80.2071],
      [13.0122, 80.2071],
      [13.0122, 80.2438],
      [12.9826, 80.2438],
    ],
  },
  {
    id: "ward-123",
    wardNumber: 123,
    wardName: "T Nagar",
    zoneName: "Zone 9",
    city: "Chennai",
    assemblyConstituency: "Thousand Lights",
    boundary: [
      [13.0226, 80.2463],
      [13.0397, 80.2463],
      [13.0397, 80.2677],
      [13.0226, 80.2677],
    ],
  },
  {
    id: "ward-108",
    wardNumber: 108,
    wardName: "Anna Nagar",
    zoneName: "Zone 8",
    city: "Chennai",
    assemblyConstituency: "Anna Nagar",
    boundary: [
      [13.0582, 80.2116],
      [13.0689, 80.2116],
      [13.0689, 80.2231],
      [13.0582, 80.2231],
    ],
  },
  {
    id: "ward-155",
    wardNumber: 155,
    wardName: "Valasaravakkam",
    zoneName: "Zone 11",
    city: "Chennai",
    assemblyConstituency: "Valasaravakkam",
    boundary: [
      [13.0222, 80.1768],
      [13.0380, 80.1768],
      [13.0380, 80.1899],
      [13.0222, 80.1899],
    ],
  },
  {
    id: "ward-072",
    wardNumber: 72,
    wardName: "Villivakkam",
    zoneName: "Zone 6",
    city: "Chennai",
    assemblyConstituency: "Villivakkam",
    boundary: [
      [13.0956, 80.2598],
      [13.1107, 80.2598],
      [13.1107, 80.2737],
      [13.0956, 80.2737],
    ],
  },
];

// Fixed reference date so server and client produce identical values (no hydration mismatch)
const REF = new Date("2026-04-26T12:00:00.000Z").getTime();
const daysAgo = (n: number) => new Date(REF - n * 86400000).toISOString();

export const mockReports: Report[] = [
  // ── Velachery (ward-174) - centroid: 12.9939, 80.2262 ── 8 reports
  {
    id: "report-1001",
    userId: "user-001",
    category: "Pothole",
    description: "Large pothole near bus stop causing two-wheeler skids.",
    lat: 12.9939,
    lng: 80.2262,
    address: "Velachery Main Road, Chennai",
    status: "open",
    supportCount: 27,
    createdAt: daysAgo(14),
    governance: { wardId: "ward-174", wardName: "Velachery", wardNumber: 174, zoneName: "Zone 13", city: "Chennai", assemblyConstituency: "Velachery" },
    imageUrls: [
      "https://images.unsplash.com/photo-1618477462146-050d2767eac4?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1590502160462-8f4c6e31f6d9?auto=format&fit=crop&w=1200&q=80",
    ],
  },
  {
    id: "report-1003",
    userId: "user-003",
    category: "Waterlogging",
    description: "Severe waterlogging after rain, knee-deep in the junction.",
    lat: 12.9955,
    lng: 80.2278,
    address: "100 Feet Road, Velachery, Chennai",
    status: "open",
    supportCount: 63,
    createdAt: daysAgo(3),
    governance: { wardId: "ward-174", wardName: "Velachery", wardNumber: 174, zoneName: "Zone 13", city: "Chennai", assemblyConstituency: "Velachery" },
    imageUrls: [
      "https://images.unsplash.com/photo-1621530108706-b3a0c6d7a02d?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1573166953836-06864dc4f9b6?auto=format&fit=crop&w=1200&q=80",
    ],
  },
  {
    id: "report-1004",
    userId: "user-004",
    category: "Streetlight Issue",
    description: "Three consecutive streetlights not working for 10 days.",
    lat: 12.9922,
    lng: 80.2244,
    address: "Velachery Lake Road, Chennai",
    status: "resolved",
    supportCount: 18,
    createdAt: daysAgo(22),
    governance: { wardId: "ward-174", wardName: "Velachery", wardNumber: 174, zoneName: "Zone 13", city: "Chennai", assemblyConstituency: "Velachery" },
    imageUrls: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1517518975577-fc6f16ce4a21?auto=format&fit=crop&w=1200&q=80",
    ],
  },
  {
    id: "report-1005",
    userId: "user-005",
    category: "Garbage",
    description: "Garbage dump right next to the school gate - health hazard.",
    lat: 12.9960,
    lng: 80.2248,
    address: "Vijaya Nagar, Velachery, Chennai",
    status: "open",
    supportCount: 44,
    createdAt: daysAgo(6),
    governance: { wardId: "ward-174", wardName: "Velachery", wardNumber: 174, zoneName: "Zone 13", city: "Chennai", assemblyConstituency: "Velachery" },
    imageUrls: [
      "https://images.unsplash.com/photo-1528323273322-d81458248d40?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1611131653297-0b0c38f68a2d?auto=format&fit=crop&w=1200&q=80",
    ],
  },
  {
    id: "report-1006",
    userId: "user-006",
    category: "Broken Footpath",
    description: "Footpath tiles broken and uplifted near BTM link road.",
    lat: 12.9928,
    lng: 80.2275,
    address: "BTM Link Road, Velachery",
    status: "open",
    supportCount: 11,
    createdAt: daysAgo(9),
    governance: { wardId: "ward-174", wardName: "Velachery", wardNumber: 174, zoneName: "Zone 13", city: "Chennai", assemblyConstituency: "Velachery" },
    imageUrls: [
      "https://images.unsplash.com/photo-1582560475093-ba66accbc424?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1517518975577-fc6f16ce4a21?auto=format&fit=crop&w=1200&q=80",
    ],
  },
  {
    id: "report-1007",
    userId: "user-007",
    category: "Drainage",
    description: "Blocked drain causing sewage overflow on the street.",
    lat: 12.9946,
    lng: 80.2238,
    address: "Velachery Market Road, Chennai",
    status: "resolved",
    supportCount: 33,
    createdAt: daysAgo(30),
    governance: { wardId: "ward-174", wardName: "Velachery", wardNumber: 174, zoneName: "Zone 13", city: "Chennai", assemblyConstituency: "Velachery" },
    imageUrls: [
      "https://images.unsplash.com/photo-1509475826633-fed577a2c71b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1573166953836-06864dc4f9b6?auto=format&fit=crop&w=1200&q=80",
    ],
  },
  {
    id: "report-1008",
    userId: "user-008",
    category: "Dust Pollution",
    description: "Construction dust from nearby site affecting residents.",
    lat: 12.9912,
    lng: 80.2270,
    address: "Taramani Link Road, Velachery",
    status: "open",
    supportCount: 7,
    createdAt: daysAgo(2),
    governance: { wardId: "ward-174", wardName: "Velachery", wardNumber: 174, zoneName: "Zone 13", city: "Chennai", assemblyConstituency: "Velachery" },
    imageUrls: [
      "https://images.unsplash.com/photo-1571156425562-12341e7c9aae?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1517518975577-fc6f16ce4a21?auto=format&fit=crop&w=1200&q=80",
    ],
  },
  {
    id: "report-1009",
    userId: "user-009",
    category: "Encroachment",
    description: "Vendor encroachment blocking footpath for pedestrians.",
    lat: 12.9948,
    lng: 80.2255,
    address: "Velachery Main Road, Near Metro",
    status: "open",
    supportCount: 15,
    createdAt: daysAgo(5),
    governance: { wardId: "ward-174", wardName: "Velachery", wardNumber: 174, zoneName: "Zone 13", city: "Chennai", assemblyConstituency: "Velachery" },
    imageUrls: [
      "https://images.unsplash.com/photo-1567521464027-f127ff144326?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1573166953836-06864dc4f9b6?auto=format&fit=crop&w=1200&q=80",
    ],
  },

  // ── T Nagar / Teynampet (ward-123) - centroid: 13.0338, 80.2594 ── 5 reports
  {
    id: "report-1002",
    userId: "user-002",
    category: "Garbage",
    description: "Overflowing bins and uncleared garbage for three days.",
    lat: 13.0338,
    lng: 80.2594,
    address: "Teynampet Main Road, Chennai",
    status: "open",
    supportCount: 41,
    createdAt: daysAgo(3),
    governance: { wardId: "ward-123", wardName: "T Nagar", wardNumber: 123, zoneName: "Zone 10", city: "Chennai", assemblyConstituency: "Thousand Lights" },
    imageUrls: [
      "https://images.unsplash.com/photo-1528323273322-d81458248d40?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1611131653297-0b0c38f68a2d?auto=format&fit=crop&w=1200&q=80",
    ],
  },
  {
    id: "report-1010",
    userId: "user-010",
    category: "Pothole",
    description: "Multiple potholes on GN Chetty Road causing accidents.",
    lat: 13.0352,
    lng: 80.2608,
    address: "GN Chetty Road, Teynampet, Chennai",
    status: "open",
    supportCount: 56,
    createdAt: daysAgo(8),
    governance: { wardId: "ward-123", wardName: "T Nagar", wardNumber: 123, zoneName: "Zone 10", city: "Chennai", assemblyConstituency: "Thousand Lights" },
    imageUrls: [
      "https://images.unsplash.com/photo-1618477462146-050d2767eac4?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1590502160462-8f4c6e31f6d9?auto=format&fit=crop&w=1200&q=80",
    ],
  },
  {
    id: "report-1011",
    userId: "user-011",
    category: "Sewage Leak",
    description: "Sewage pipe burst near Nungambakkam subway - foul smell.",
    lat: 13.0322,
    lng: 80.2578,
    address: "Nungambakkam High Road, Chennai",
    status: "open",
    supportCount: 88,
    createdAt: daysAgo(1),
    governance: { wardId: "ward-123", wardName: "T Nagar", wardNumber: 123, zoneName: "Zone 10", city: "Chennai", assemblyConstituency: "Thousand Lights" },
    imageUrls: [
      "https://images.unsplash.com/photo-1509475826633-fed577a2c71b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1573166953836-06864dc4f9b6?auto=format&fit=crop&w=1200&q=80",
    ],
  },
  {
    id: "report-1012",
    userId: "user-012",
    category: "Streetlight Issue",
    description: "Bus stop streetlight broken - unsafe at night.",
    lat: 13.0344,
    lng: 80.2572,
    address: "Thyagaraya Road, Teynampet",
    status: "resolved",
    supportCount: 22,
    createdAt: daysAgo(20),
    governance: { wardId: "ward-123", wardName: "T Nagar", wardNumber: 123, zoneName: "Zone 10", city: "Chennai", assemblyConstituency: "Thousand Lights" },
    imageUrls: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1517518975577-fc6f16ce4a21?auto=format&fit=crop&w=1200&q=80",
    ],
  },
  {
    id: "report-1013",
    userId: "user-013",
    category: "Encroachment",
    description: "Shops encroaching on pedestrian pathway near the market.",
    lat: 13.0358,
    lng: 80.2582,
    address: "Chamiers Road, Teynampet",
    status: "open",
    supportCount: 31,
    createdAt: daysAgo(11),
    governance: { wardId: "ward-123", wardName: "T Nagar", wardNumber: 123, zoneName: "Zone 10", city: "Chennai", assemblyConstituency: "Thousand Lights" },
    imageUrls: [
      "https://images.unsplash.com/photo-1567521464027-f127ff144326?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1611131653297-0b0c38f68a2d?auto=format&fit=crop&w=1200&q=80",
    ],
  },

  // ── Anna Nagar / Arumbakkam (ward-108) - centroid: 13.0633, 80.2172 ── 4 reports
  {
    id: "report-1014",
    userId: "user-014",
    category: "Waterlogging",
    description: "Anna Nagar underpass floods during rain - knee-deep water.",
    lat: 13.0633,
    lng: 80.2172,
    address: "Arumbakkam Main Road, Chennai",
    status: "open",
    supportCount: 74,
    createdAt: daysAgo(4),
    governance: { wardId: "ward-108", wardName: "Anna Nagar", wardNumber: 108, zoneName: "Zone 8", city: "Chennai", assemblyConstituency: "Anna Nagar" },
    imageUrls: [
      "https://images.unsplash.com/photo-1621530108706-b3a0c6d7a02d?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1573166953836-06864dc4f9b6?auto=format&fit=crop&w=1200&q=80",
    ],
  },
  {
    id: "report-1015",
    userId: "user-015",
    category: "Garbage",
    description: "No garbage collection for 5 days in the colony.",
    lat: 13.0645,
    lng: 80.2185,
    address: "Shanthi Colony, Arumbakkam",
    status: "open",
    supportCount: 39,
    createdAt: daysAgo(5),
    governance: { wardId: "ward-108", wardName: "Anna Nagar", wardNumber: 108, zoneName: "Zone 8", city: "Chennai", assemblyConstituency: "Anna Nagar" },
    imageUrls: [
      "https://images.unsplash.com/photo-1528323273322-d81458248d40?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1611131653297-0b0c38f68a2d?auto=format&fit=crop&w=1200&q=80",
    ],
  },
  {
    id: "report-1016",
    userId: "user-016",
    category: "Pothole",
    description: "Deep crater on main road - vehicles swerving dangerously.",
    lat: 13.0620,
    lng: 80.2158,
    address: "Anna Nagar Main Road, Chennai",
    status: "resolved",
    supportCount: 51,
    createdAt: daysAgo(25),
    governance: { wardId: "ward-108", wardName: "Anna Nagar", wardNumber: 108, zoneName: "Zone 8", city: "Chennai", assemblyConstituency: "Anna Nagar" },
    imageUrls: [
      "https://images.unsplash.com/photo-1618477462146-050d2767eac4?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1590502160462-8f4c6e31f6d9?auto=format&fit=crop&w=1200&q=80",
    ],
  },
  {
    id: "report-1017",
    userId: "user-017",
    category: "Streetlight Issue",
    description: "Entire street dark since last week - no response from GCC.",
    lat: 13.0642,
    lng: 80.2162,
    address: "12th Main Road, Anna Nagar West",
    status: "open",
    supportCount: 29,
    createdAt: daysAgo(7),
    governance: { wardId: "ward-108", wardName: "Anna Nagar", wardNumber: 108, zoneName: "Zone 8", city: "Chennai", assemblyConstituency: "Anna Nagar" },
    imageUrls: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1517518975577-fc6f16ce4a21?auto=format&fit=crop&w=1200&q=80",
    ],
  },

  // ── Valasaravakkam (ward-155) - centroid: 13.0286, 80.1841 ── 3 reports
  {
    id: "report-1018",
    userId: "user-018",
    category: "Sewage Leak",
    description: "Sewage pipe burst near Valasaravakkam signal - foul smell.",
    lat: 13.0286,
    lng: 80.1841,
    address: "Valasaravakkam Main Road, Chennai",
    status: "open",
    supportCount: 95,
    createdAt: daysAgo(2),
    governance: { wardId: "ward-155", wardName: "Valasaravakkam", wardNumber: 155, zoneName: "Zone 11", city: "Chennai", assemblyConstituency: "Valasaravakkam" },
    imageUrls: [
      "https://images.unsplash.com/photo-1509475826633-fed577a2c71b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1573166953836-06864dc4f9b6?auto=format&fit=crop&w=1200&q=80",
    ],
  },
  {
    id: "report-1019",
    userId: "user-019",
    category: "Broken Footpath",
    description: "Footpath tiles completely broken - elderly at risk of falling.",
    lat: 13.0300,
    lng: 80.1855,
    address: "Arcot Road, Valasaravakkam",
    status: "resolved",
    supportCount: 16,
    createdAt: daysAgo(18),
    governance: { wardId: "ward-155", wardName: "Valasaravakkam", wardNumber: 155, zoneName: "Zone 11", city: "Chennai", assemblyConstituency: "Valasaravakkam" },
    imageUrls: [
      "https://images.unsplash.com/photo-1582560475093-ba66accbc424?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1517518975577-fc6f16ce4a21?auto=format&fit=crop&w=1200&q=80",
    ],
  },
  {
    id: "report-1020",
    userId: "user-020",
    category: "Garbage",
    description: "Waste dump near the colony entrance not cleared for a week.",
    lat: 13.0270,
    lng: 80.1828,
    address: "Valasaravakkam Colony, Chennai",
    status: "open",
    supportCount: 48,
    createdAt: daysAgo(6),
    governance: { wardId: "ward-155", wardName: "Valasaravakkam", wardNumber: 155, zoneName: "Zone 11", city: "Chennai", assemblyConstituency: "Valasaravakkam" },
    imageUrls: [
      "https://images.unsplash.com/photo-1528323273322-d81458248d40?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1611131653297-0b0c38f68a2d?auto=format&fit=crop&w=1200&q=80",
    ],
  },

  // ── Villivakkam / Thiru Vi Ka Nagar (ward-072) - centroid: 13.1032, 80.2664 ── 2 reports
  {
    id: "report-1021",
    userId: "user-021",
    category: "Waterlogging",
    description: "Waterlogging at the junction after every rain - standing water for days.",
    lat: 13.1032,
    lng: 80.2664,
    address: "Villivakkam Main Road, Chennai",
    status: "open",
    supportCount: 112,
    createdAt: daysAgo(1),
    governance: { wardId: "ward-072", wardName: "Villivakkam", wardNumber: 72, zoneName: "Zone 6", city: "Chennai", assemblyConstituency: "Villivakkam" },
    imageUrls: [
      "https://images.unsplash.com/photo-1621530108706-b3a0c6d7a02d?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1573166953836-06864dc4f9b6?auto=format&fit=crop&w=1200&q=80",
    ],
  },
  {
    id: "report-1022",
    userId: "user-022",
    category: "Pothole",
    description: "Deep potholes on the arterial road causing vehicle damage.",
    lat: 13.1048,
    lng: 80.2680,
    address: "Villivakkam–Ayanavaram Road, Chennai",
    status: "open",
    supportCount: 67,
    createdAt: daysAgo(4),
    governance: { wardId: "ward-072", wardName: "Villivakkam", wardNumber: 72, zoneName: "Zone 6", city: "Chennai", assemblyConstituency: "Villivakkam" },
    imageUrls: [
      "https://images.unsplash.com/photo-1618477462146-050d2767eac4?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1590502160462-8f4c6e31f6d9?auto=format&fit=crop&w=1200&q=80",
    ],
  },
];

export const wardRepresentatives: Representative[] = [
  {
    id: "rep-ward-174-councillor",
    name: "R. Lakshmi",
    role: "Councillor",
    wardId: "ward-174",
    area: "Velachery Ward 174",
    constituency: "Velachery Ward",
    party: "DMK",
    partyColor: "#e3000f",
    photoUrl: "https://api.dicebear.com/9.x/initials/svg?seed=R%20Lakshmi&backgroundColor=fecaca&fontFamily=Arial&fontSize=40",
    email: "councillor.174@gcc.tn.gov.in",
    helpline: "044-2243-1174",
    officeHours: "Mon-Sat, 10:00 AM – 5:00 PM",
    preferredChannel: "phone",
  },
  // ── Velachery (ward-174) ──
  {
    id: "rep-ward-174-engineer",
    name: "S. Arunkumar",
    role: "WardEngineer",
    wardId: "ward-174",
    area: "Velachery",
    constituency: "GCC Zone 13 – Ward 174",
    photoUrl: "https://api.dicebear.com/9.x/initials/svg?seed=S%20Arunkumar&backgroundColor=bfdbfe&fontFamily=Arial&fontSize=40",
    email: "wardengineer.174@gcc.tn.gov.in",
    helpline: "1913",
    officeHours: "Mon–Fri, 9:30 AM – 6:00 PM",
    preferredChannel: "email",
  },
  {
    id: "rep-ward-174-sanitary",
    name: "P. Uma",
    role: "SanitaryInspector",
    wardId: "ward-174",
    area: "Velachery",
    constituency: "GCC Zone 13 – Ward 174",
    photoUrl: "https://api.dicebear.com/9.x/initials/svg?seed=P%20Uma&backgroundColor=bbf7d0&fontFamily=Arial&fontSize=40",
    email: "sanitary.174@gcc.tn.gov.in",
    helpline: "1913",
    officeHours: "Mon–Sat, 7:00 AM – 2:00 PM",
    preferredChannel: "phone",
  },
  {
    id: "rep-ward-174-mla",
    name: "K. Senthil Kumar",
    role: "MLA",
    wardId: "ward-174",
    area: "Velachery Constituency",
    constituency: "Velachery Assembly Constituency",
    party: "DMK",
    partyColor: "#e3000f",
    photoUrl: "https://api.dicebear.com/9.x/initials/svg?seed=K%20Senthil&backgroundColor=fecaca&fontFamily=Arial&fontSize=40",
    email: "mla.velachery@tnassembly.tn.gov.in",
    helpline: "044-2356-1174",
    officeHours: "Tue–Sat, 11:00 AM – 4:00 PM",
    preferredChannel: "email",
  },
  {
    id: "rep-ward-174-mp",
    name: "M. Prakash",
    role: "MP",
    wardId: "ward-174",
    area: "South Chennai Lok Sabha",
    constituency: "South Chennai Parliamentary Constituency",
    party: "INC",
    partyColor: "#1a6fc4",
    photoUrl: "https://api.dicebear.com/9.x/initials/svg?seed=M%20Prakash&backgroundColor=bfdbfe&fontFamily=Arial&fontSize=40",
    email: "mp.southchennai@sansad.nic.in",
    helpline: "011-2337-8174",
    officeHours: "Mon–Fri, 11:00 AM – 5:00 PM",
    preferredChannel: "email",
  },
  {
    id: "rep-ward-174-zonal",
    name: "D. Revathi",
    role: "ZonalOfficer",
    wardId: "ward-174",
    area: "Zone 13",
    constituency: "GCC Zone 13 Office",
    photoUrl: "https://api.dicebear.com/9.x/initials/svg?seed=D%20Revathi&backgroundColor=e9d5ff&fontFamily=Arial&fontSize=40",
    email: "zone13@gcc.tn.gov.in",
    helpline: "044-2233-1013",
    officeHours: "Mon–Fri, 10:00 AM – 5:30 PM",
    preferredChannel: "phone",
  },

  // ── T Nagar (ward-123) ──
  {
    id: "rep-ward-123-councillor",
    name: "N. Vinodhini",
    role: "Councillor",
    wardId: "ward-123",
    area: "T Nagar Ward 123",
    constituency: "T Nagar Ward",
    party: "AIADMK",
    partyColor: "#006400",
    photoUrl: "https://api.dicebear.com/9.x/initials/svg?seed=N%20Vinodhini&backgroundColor=bbf7d0&fontFamily=Arial&fontSize=40",
    email: "councillor.123@gcc.tn.gov.in",
    helpline: "044-2243-1123",
    officeHours: "Mon–Sat, 10:00 AM – 5:00 PM",
    preferredChannel: "phone",
  },
  {
    id: "rep-ward-123-engineer",
    name: "R. Jayachandran",
    role: "WardEngineer",
    wardId: "ward-123",
    area: "T Nagar",
    constituency: "GCC Zone 9 – Ward 123",
    photoUrl: "https://api.dicebear.com/9.x/initials/svg?seed=R%20Jayachandran&backgroundColor=bfdbfe&fontFamily=Arial&fontSize=40",
    email: "wardengineer.123@gcc.tn.gov.in",
    helpline: "1913",
    officeHours: "Mon–Fri, 9:30 AM – 6:00 PM",
    preferredChannel: "email",
  },
  {
    id: "rep-ward-123-sanitary",
    name: "A. Hema",
    role: "SanitaryInspector",
    wardId: "ward-123",
    area: "T Nagar",
    constituency: "GCC Zone 9 – Ward 123",
    photoUrl: "https://api.dicebear.com/9.x/initials/svg?seed=A%20Hema&backgroundColor=bbf7d0&fontFamily=Arial&fontSize=40",
    email: "sanitary.123@gcc.tn.gov.in",
    helpline: "1913",
    officeHours: "Mon–Sat, 7:00 AM – 2:00 PM",
    preferredChannel: "phone",
  },
  {
    id: "rep-ward-123-mla",
    name: "V. Harish",
    role: "MLA",
    wardId: "ward-123",
    area: "Thousand Lights Constituency",
    constituency: "Thousand Lights Assembly Constituency",
    party: "DMK",
    partyColor: "#e3000f",
    photoUrl: "https://api.dicebear.com/9.x/initials/svg?seed=V%20Harish&backgroundColor=fecaca&fontFamily=Arial&fontSize=40",
    email: "mla.thousandlights@tnassembly.tn.gov.in",
    helpline: "044-2356-1123",
    officeHours: "Tue–Sat, 11:00 AM – 4:00 PM",
    preferredChannel: "email",
  },
  {
    id: "rep-ward-123-mp",
    name: "S. Nandhakumar",
    role: "MP",
    wardId: "ward-123",
    area: "Central Chennai Lok Sabha",
    constituency: "Central Chennai Parliamentary Constituency",
    party: "BJP",
    partyColor: "#ff6600",
    photoUrl: "https://api.dicebear.com/9.x/initials/svg?seed=S%20Nandhakumar&backgroundColor=fed7aa&fontFamily=Arial&fontSize=40",
    email: "mp.centralchennai@sansad.nic.in",
    helpline: "011-2337-8123",
    officeHours: "Mon–Fri, 11:00 AM – 5:00 PM",
    preferredChannel: "email",
  },
  {
    id: "rep-ward-123-zonal",
    name: "L. Krithika",
    role: "ZonalOfficer",
    wardId: "ward-123",
    area: "Zone 9",
    constituency: "GCC Zone 9 Office",
    photoUrl: "https://api.dicebear.com/9.x/initials/svg?seed=L%20Krithika&backgroundColor=e9d5ff&fontFamily=Arial&fontSize=40",
    email: "zone9@gcc.tn.gov.in",
    helpline: "044-2233-1009",
    officeHours: "Mon–Fri, 10:00 AM – 5:30 PM",
    preferredChannel: "phone",
  },

  // ── Anna Nagar (ward-108) ──
  {
    id: "rep-ward-108-councillor",
    name: "T. Bharathi",
    role: "Councillor",
    wardId: "ward-108",
    area: "Anna Nagar Ward 108",
    constituency: "Anna Nagar Ward",
    party: "DMK",
    partyColor: "#e3000f",
    photoUrl: "https://api.dicebear.com/9.x/initials/svg?seed=T%20Bharathi&backgroundColor=fecaca&fontFamily=Arial&fontSize=40",
    email: "councillor.108@gcc.tn.gov.in",
    helpline: "044-2243-1108",
    officeHours: "Mon–Sat, 10:00 AM – 5:00 PM",
    preferredChannel: "phone",
  },
  {
    id: "rep-ward-108-engineer",
    name: "G. Selvam",
    role: "WardEngineer",
    wardId: "ward-108",
    area: "Anna Nagar",
    constituency: "GCC Zone 8 – Ward 108",
    photoUrl: "https://api.dicebear.com/9.x/initials/svg?seed=G%20Selvam&backgroundColor=bfdbfe&fontFamily=Arial&fontSize=40",
    email: "wardengineer.108@gcc.tn.gov.in",
    helpline: "1913",
    officeHours: "Mon–Fri, 9:30 AM – 6:00 PM",
    preferredChannel: "email",
  },
  {
    id: "rep-ward-108-sanitary",
    name: "M. Kavitha",
    role: "SanitaryInspector",
    wardId: "ward-108",
    area: "Anna Nagar",
    constituency: "GCC Zone 8 – Ward 108",
    photoUrl: "https://api.dicebear.com/9.x/initials/svg?seed=M%20Kavitha&backgroundColor=bbf7d0&fontFamily=Arial&fontSize=40",
    email: "sanitary.108@gcc.tn.gov.in",
    helpline: "1913",
    officeHours: "Mon–Sat, 7:00 AM – 2:00 PM",
    preferredChannel: "phone",
  },
  {
    id: "rep-ward-108-mla",
    name: "R. Balakrishnan",
    role: "MLA",
    wardId: "ward-108",
    area: "Anna Nagar Constituency",
    constituency: "Anna Nagar Assembly Constituency",
    party: "AIADMK",
    partyColor: "#006400",
    photoUrl: "https://api.dicebear.com/9.x/initials/svg?seed=R%20Balakrishnan&backgroundColor=bbf7d0&fontFamily=Arial&fontSize=40",
    email: "mla.annanagar@tnassembly.tn.gov.in",
    helpline: "044-2356-1108",
    officeHours: "Tue–Sat, 11:00 AM – 4:00 PM",
    preferredChannel: "phone",
  },
  {
    id: "rep-ward-108-mp",
    name: "P. Thiyagarajan",
    role: "MP",
    wardId: "ward-108",
    area: "North Chennai Lok Sabha",
    constituency: "North Chennai Parliamentary Constituency",
    party: "DMK",
    partyColor: "#e3000f",
    photoUrl: "https://api.dicebear.com/9.x/initials/svg?seed=P%20Thiyagarajan&backgroundColor=fecaca&fontFamily=Arial&fontSize=40",
    email: "mp.northchennai@sansad.nic.in",
    helpline: "011-2337-8108",
    officeHours: "Mon–Fri, 11:00 AM – 5:00 PM",
    preferredChannel: "email",
  },
  {
    id: "rep-ward-108-zonal",
    name: "S. Meenakshi",
    role: "ZonalOfficer",
    wardId: "ward-108",
    area: "Zone 8",
    constituency: "GCC Zone 8 Office",
    photoUrl: "https://api.dicebear.com/9.x/initials/svg?seed=S%20Meenakshi&backgroundColor=e9d5ff&fontFamily=Arial&fontSize=40",
    email: "zone8@gcc.tn.gov.in",
    helpline: "044-2233-1008",
    officeHours: "Mon–Fri, 10:00 AM – 5:30 PM",
    preferredChannel: "phone",
  },

  // ── Valasaravakkam (ward-155) ──
  {
    id: "rep-ward-155-councillor",
    name: "J. Anitha",
    role: "Councillor",
    wardId: "ward-155",
    area: "Valasaravakkam Ward 155",
    constituency: "Valasaravakkam Ward",
    party: "DMK",
    partyColor: "#e3000f",
    photoUrl: "https://api.dicebear.com/9.x/initials/svg?seed=J%20Anitha&backgroundColor=fecaca&fontFamily=Arial&fontSize=40",
    email: "councillor.155@gcc.tn.gov.in",
    helpline: "044-2243-1155",
    officeHours: "Mon–Sat, 10:00 AM – 5:00 PM",
    preferredChannel: "phone",
  },
  {
    id: "rep-ward-155-engineer",
    name: "K. Rajendran",
    role: "WardEngineer",
    wardId: "ward-155",
    area: "Valasaravakkam",
    constituency: "GCC Zone 11 – Ward 155",
    photoUrl: "https://api.dicebear.com/9.x/initials/svg?seed=K%20Rajendran&backgroundColor=bfdbfe&fontFamily=Arial&fontSize=40",
    email: "wardengineer.155@gcc.tn.gov.in",
    helpline: "1913",
    officeHours: "Mon–Fri, 9:30 AM – 6:00 PM",
    preferredChannel: "email",
  },
  {
    id: "rep-ward-155-sanitary",
    name: "V. Sudha",
    role: "SanitaryInspector",
    wardId: "ward-155",
    area: "Valasaravakkam",
    constituency: "GCC Zone 11 – Ward 155",
    photoUrl: "https://api.dicebear.com/9.x/initials/svg?seed=V%20Sudha&backgroundColor=bbf7d0&fontFamily=Arial&fontSize=40",
    email: "sanitary.155@gcc.tn.gov.in",
    helpline: "1913",
    officeHours: "Mon–Sat, 7:00 AM – 2:00 PM",
    preferredChannel: "phone",
  },
  {
    id: "rep-ward-155-mla",
    name: "N. Sathyamurthy",
    role: "MLA",
    wardId: "ward-155",
    area: "Valasaravakkam Constituency",
    constituency: "Valasaravakkam Assembly Constituency",
    party: "DMK",
    partyColor: "#e3000f",
    photoUrl: "https://api.dicebear.com/9.x/initials/svg?seed=N%20Sathyamurthy&backgroundColor=fecaca&fontFamily=Arial&fontSize=40",
    email: "mla.valasaravakkam@tnassembly.tn.gov.in",
    helpline: "044-2356-1155",
    officeHours: "Tue–Sat, 11:00 AM – 4:00 PM",
    preferredChannel: "email",
  },
  {
    id: "rep-ward-155-mp",
    name: "D. Kanimozhi",
    role: "MP",
    wardId: "ward-155",
    area: "South Chennai Lok Sabha",
    constituency: "South Chennai Parliamentary Constituency",
    party: "DMK",
    partyColor: "#e3000f",
    photoUrl: "https://api.dicebear.com/9.x/initials/svg?seed=D%20Kanimozhi&backgroundColor=fecaca&fontFamily=Arial&fontSize=40",
    email: "mp.southchennai@sansad.nic.in",
    helpline: "011-2337-8155",
    officeHours: "Mon–Fri, 11:00 AM – 5:00 PM",
    preferredChannel: "email",
  },
  {
    id: "rep-ward-155-zonal",
    name: "A. Pradeep",
    role: "ZonalOfficer",
    wardId: "ward-155",
    area: "Zone 11",
    constituency: "GCC Zone 11 Office",
    photoUrl: "https://api.dicebear.com/9.x/initials/svg?seed=A%20Pradeep&backgroundColor=e9d5ff&fontFamily=Arial&fontSize=40",
    email: "zone11@gcc.tn.gov.in",
    helpline: "044-2233-1011",
    officeHours: "Mon–Fri, 10:00 AM – 5:30 PM",
    preferredChannel: "phone",
  },

  // ── Villivakkam (ward-072) ──
  {
    id: "rep-ward-072-councillor",
    name: "C. Murugan",
    role: "Councillor",
    wardId: "ward-072",
    area: "Villivakkam Ward 72",
    constituency: "Villivakkam Ward",
    party: "DMK",
    partyColor: "#e3000f",
    photoUrl: "https://api.dicebear.com/9.x/initials/svg?seed=C%20Murugan&backgroundColor=fecaca&fontFamily=Arial&fontSize=40",
    email: "councillor.072@gcc.tn.gov.in",
    helpline: "044-2243-1072",
    officeHours: "Mon–Sat, 10:00 AM – 5:00 PM",
    preferredChannel: "phone",
  },
  {
    id: "rep-ward-072-engineer",
    name: "B. Suresh",
    role: "WardEngineer",
    wardId: "ward-072",
    area: "Villivakkam",
    constituency: "GCC Zone 6 – Ward 72",
    photoUrl: "https://api.dicebear.com/9.x/initials/svg?seed=B%20Suresh&backgroundColor=bfdbfe&fontFamily=Arial&fontSize=40",
    email: "wardengineer.072@gcc.tn.gov.in",
    helpline: "1913",
    officeHours: "Mon–Fri, 9:30 AM – 6:00 PM",
    preferredChannel: "email",
  },
  {
    id: "rep-ward-072-sanitary",
    name: "R. Poongodi",
    role: "SanitaryInspector",
    wardId: "ward-072",
    area: "Villivakkam",
    constituency: "GCC Zone 6 – Ward 72",
    photoUrl: "https://api.dicebear.com/9.x/initials/svg?seed=R%20Poongodi&backgroundColor=bbf7d0&fontFamily=Arial&fontSize=40",
    email: "sanitary.072@gcc.tn.gov.in",
    helpline: "1913",
    officeHours: "Mon–Sat, 7:00 AM – 2:00 PM",
    preferredChannel: "phone",
  },
  {
    id: "rep-ward-072-mla",
    name: "S. Ezhilarasan",
    role: "MLA",
    wardId: "ward-072",
    area: "Villivakkam Constituency",
    constituency: "Villivakkam Assembly Constituency",
    party: "DMK",
    partyColor: "#e3000f",
    photoUrl: "https://api.dicebear.com/9.x/initials/svg?seed=S%20Ezhilarasan&backgroundColor=fecaca&fontFamily=Arial&fontSize=40",
    email: "mla.villivakkam@tnassembly.tn.gov.in",
    helpline: "044-2356-1072",
    officeHours: "Tue–Sat, 11:00 AM – 4:00 PM",
    preferredChannel: "phone",
  },
  {
    id: "rep-ward-072-mp",
    name: "V. Dayanidhi Maran",
    role: "MP",
    wardId: "ward-072",
    area: "West Chennai Lok Sabha",
    constituency: "West Chennai Parliamentary Constituency",
    party: "DMK",
    partyColor: "#e3000f",
    photoUrl: "https://api.dicebear.com/9.x/initials/svg?seed=V%20Dayanidhi&backgroundColor=fecaca&fontFamily=Arial&fontSize=40",
    email: "mp.westchennai@sansad.nic.in",
    helpline: "011-2337-8072",
    officeHours: "Mon–Fri, 11:00 AM – 5:00 PM",
    preferredChannel: "email",
  },
  {
    id: "rep-ward-072-zonal",
    name: "P. Anbazhagan",
    role: "ZonalOfficer",
    wardId: "ward-072",
    area: "Zone 6",
    constituency: "GCC Zone 6 Office",
    photoUrl: "https://api.dicebear.com/9.x/initials/svg?seed=P%20Anbazhagan&backgroundColor=e9d5ff&fontFamily=Arial&fontSize=40",
    email: "zone6@gcc.tn.gov.in",
    helpline: "044-2233-1006",
    officeHours: "Mon–Fri, 10:00 AM – 5:30 PM",
    preferredChannel: "phone",
  },
];

export const responsibilityByCategory: IssueResponsibility[] = [
  {
    category: "Pothole",
    primaryRole: "WardEngineer",
    escalationOrder: ["WardEngineer", "ZonalOfficer", "Councillor", "MLA", "MP"],
  },
  {
    category: "Garbage",
    primaryRole: "SanitaryInspector",
    escalationOrder: ["SanitaryInspector", "ZonalOfficer", "Councillor", "MLA", "MP"],
  },
  {
    category: "Broken Footpath",
    primaryRole: "WardEngineer",
    escalationOrder: ["WardEngineer", "ZonalOfficer", "Councillor", "MLA", "MP"],
  },
  {
    category: "Dust Pollution",
    primaryRole: "SanitaryInspector",
    escalationOrder: ["SanitaryInspector", "ZonalOfficer", "Councillor", "MLA", "MP"],
  },
  {
    category: "Waterlogging",
    primaryRole: "WardEngineer",
    escalationOrder: ["WardEngineer", "ZonalOfficer", "Councillor", "MLA", "MP"],
  },
  {
    category: "Sewage Leak",
    primaryRole: "WardEngineer",
    escalationOrder: ["WardEngineer", "ZonalOfficer", "Councillor", "MLA", "MP"],
  },
  {
    category: "Streetlight Issue",
    primaryRole: "WardEngineer",
    escalationOrder: ["WardEngineer", "ZonalOfficer", "Councillor", "MLA", "MP"],
  },
  {
    category: "Encroachment",
    primaryRole: "Councillor",
    escalationOrder: ["Councillor", "ZonalOfficer", "MLA", "MP"],
  },
  {
    category: "Drainage",
    primaryRole: "WardEngineer",
    escalationOrder: ["WardEngineer", "ZonalOfficer", "Councillor", "MLA", "MP"],
  },
  {
    category: "Other",
    primaryRole: "Councillor",
    escalationOrder: ["Councillor", "ZonalOfficer", "MLA", "MP"],
  },
];

export const escalationSteps: Record<RepresentativeRole, EscalationStep> = {
  Councillor: {
    role: "Councillor",
    stepTitle: "Ward-level elected representative",
    responseTargetHours: 24,
  },
  WardEngineer: {
    role: "WardEngineer",
    stepTitle: "Ward engineering operations",
    responseTargetHours: 24,
  },
  SanitaryInspector: {
    role: "SanitaryInspector",
    stepTitle: "Sanitation field operations",
    responseTargetHours: 12,
  },
  ZonalOfficer: {
    role: "ZonalOfficer",
    stepTitle: "Zone-level escalation authority",
    responseTargetHours: 48,
  },
  MLA: {
    role: "MLA",
    stepTitle: "Assembly constituency escalation",
    responseTargetHours: 72,
  },
  MP: {
    role: "MP",
    stepTitle: "Parliamentary constituency escalation",
    responseTargetHours: 96,
  },
};
