-- Chennai GCC elected councillors (2022 urban local body elections).
-- Regenerate: node scripts/import-chennai-councillors.mjs
-- Source: https://github.com/elseasama/OpenDataChennai (chnresult2022.csv)
-- Contact fields use GCC corporate helpline/email; per-councillor contacts are not in the public dataset.

insert into public.representatives (
  id, ward_id, name, role, area, constituency, party, party_color, photo_url,
  email, helpline, office_hours, preferred_channel
)
values
  ('rep-ward-001-councillor', 'ward-001', 'Sivakumar', 'Councillor',
   'Ward 1, Zone Thiruvottiyur', 'GCC Ward 1',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Sivakumar&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-002-councillor', 'ward-002', 'Gomathi Santhoshkumar', 'Councillor',
   'Ward 2, Zone Thiruvottiyur', 'GCC Ward 2',
   'Independent', '#64748b', 'https://api.dicebear.com/9.x/initials/svg?seed=Gomathi%20Santhoshkumar&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-003-councillor', 'ward-003', 'Tamizharasan', 'Councillor',
   'Ward 3, Zone Thiruvottiyur', 'GCC Ward 3',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Tamizharasan&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-004-councillor', 'ward-004', 'Jayaraman', 'Councillor',
   'Ward 4, Zone Thiruvottiyur', 'GCC Ward 4',
   'CPI(M)', '#b91c1c', 'https://api.dicebear.com/9.x/initials/svg?seed=Jayaraman&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-005-councillor', 'ward-005', 'Shokalingam', 'Councillor',
   'Ward 5, Zone Thiruvottiyur', 'GCC Ward 5',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Shokalingam&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-006-councillor', 'ward-006', 'Samuel Thriviyam', 'Councillor',
   'Ward 6, Zone Thiruvottiyur', 'GCC Ward 6',
   'INC', '#1a6fc4', 'https://api.dicebear.com/9.x/initials/svg?seed=Samuel%20Thriviyam&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-007-councillor', 'ward-007', 'Karthik', 'Councillor',
   'Ward 7, Zone Thiruvottiyur', 'GCC Ward 7',
   'AIADMK', '#006400', 'https://api.dicebear.com/9.x/initials/svg?seed=Karthik&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-008-councillor', 'ward-008', 'Rajakumari', 'Councillor',
   'Ward 8, Zone Thiruvottiyur', 'GCC Ward 8',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Rajakumari&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-009-councillor', 'ward-009', 'Uma Saravanan', 'Councillor',
   'Ward 9, Zone Thiruvottiyur', 'GCC Ward 9',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Uma%20Saravanan&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-010-councillor', 'ward-010', 'Thaniyarasu', 'Councillor',
   'Ward 10, Zone Thiruvottiyur', 'GCC Ward 10',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Thaniyarasu&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-011-councillor', 'ward-011', 'Saranya', 'Councillor',
   'Ward 11, Zone Thiruvottiyur', 'GCC Ward 11',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Saranya&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-012-councillor', 'ward-012', 'Kavi Ganesan', 'Councillor',
   'Ward 12, Zone Thiruvottiyur', 'GCC Ward 12',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Kavi%20Ganesan&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-013-councillor', 'ward-013', 'Susila', 'Councillor',
   'Ward 13, Zone Thiruvottiyur', 'GCC Ward 13',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Susila&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-014-councillor', 'ward-014', 'Banumathi', 'Councillor',
   'Ward 14, Zone Thiruvottiyur', 'GCC Ward 14',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Banumathi&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-015-councillor', 'ward-015', 'Nandhini', 'Councillor',
   'Ward 15, Zone Manali', 'GCC Ward 15',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Nandhini&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-016-councillor', 'ward-016', 'Rajendran', 'Councillor',
   'Ward 16, Zone Manali', 'GCC Ward 16',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Rajendran&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-017-councillor', 'ward-017', 'Jayashankar', 'Councillor',
   'Ward 17, Zone Manali', 'GCC Ward 17',
   'AIADMK', '#006400', 'https://api.dicebear.com/9.x/initials/svg?seed=Jayashankar&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-018-councillor', 'ward-018', 'Sridharan', 'Councillor',
   'Ward 18, Zone Manali', 'GCC Ward 18',
   'AIADMK', '#006400', 'https://api.dicebear.com/9.x/initials/svg?seed=Sridharan&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-019-councillor', 'ward-019', 'Kasinathan', 'Councillor',
   'Ward 19, Zone Manali', 'GCC Ward 19',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Kasinathan&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-020-councillor', 'ward-020', 'Arumugam', 'Councillor',
   'Ward 20, Zone Manali', 'GCC Ward 20',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Arumugam&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-021-councillor', 'ward-021', 'Rajesh Sekar', 'Councillor',
   'Ward 21, Zone Manali', 'GCC Ward 21',
   'AIADMK', '#006400', 'https://api.dicebear.com/9.x/initials/svg?seed=Rajesh%20Sekar&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-022-councillor', 'ward-022', 'Theerthy', 'Councillor',
   'Ward 22, Zone Madhavaram', 'GCC Ward 22',
   'INC', '#1a6fc4', 'https://api.dicebear.com/9.x/initials/svg?seed=Theerthy&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-023-councillor', 'ward-023', 'Rajan', 'Councillor',
   'Ward 23, Zone Madhavaram', 'GCC Ward 23',
   'Independent', '#64748b', 'https://api.dicebear.com/9.x/initials/svg?seed=Rajan&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-024-councillor', 'ward-024', 'Settu', 'Councillor',
   'Ward 24, Zone Madhavaram', 'GCC Ward 24',
   'AIADMK', '#006400', 'https://api.dicebear.com/9.x/initials/svg?seed=Settu&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-025-councillor', 'ward-025', 'Nandhagopal', 'Councillor',
   'Ward 25, Zone Madhavaram', 'GCC Ward 25',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Nandhagopal&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-026-councillor', 'ward-026', 'Ashana Merisha.j', 'Councillor',
   'Ward 26, Zone Madhavaram', 'GCC Ward 26',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Ashana%20Merisha.j&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-027-councillor', 'ward-027', 'Chadran', 'Councillor',
   'Ward 27, Zone Madhavaram', 'GCC Ward 27',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Chadran&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-028-councillor', 'ward-028', 'Kanimozhi', 'Councillor',
   'Ward 28, Zone Madhavaram', 'GCC Ward 28',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Kanimozhi&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-029-councillor', 'ward-029', 'Karthikeyan', 'Councillor',
   'Ward 29, Zone Madhavaram', 'GCC Ward 29',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Karthikeyan&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-030-councillor', 'ward-030', 'Duraiswamy', 'Councillor',
   'Ward 30, Zone Madhavaram', 'GCC Ward 30',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Duraiswamy&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-031-councillor', 'ward-031', 'Sangeetha', 'Councillor',
   'Ward 31, Zone Madhavaram', 'GCC Ward 31',
   'INC', '#1a6fc4', 'https://api.dicebear.com/9.x/initials/svg?seed=Sangeetha&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-032-councillor', 'ward-032', 'Elumalai', 'Councillor',
   'Ward 32, Zone Madhavaram', 'GCC Ward 32',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Elumalai&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-033-councillor', 'ward-033', 'Guna Sundari', 'Councillor',
   'Ward 33, Zone Madhavaram', 'GCC Ward 33',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Guna%20Sundari&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-034-councillor', 'ward-034', 'Shamila Gandhi', 'Councillor',
   'Ward 34, Zone Tondiarpet', 'GCC Ward 34',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Shamila%20Gandhi&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-035-councillor', 'ward-035', 'Jeevan', 'Councillor',
   'Ward 35, Zone Tondiarpet', 'GCC Ward 35',
   'MDMK', '#991b1b', 'https://api.dicebear.com/9.x/initials/svg?seed=Jeevan&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-036-councillor', 'ward-036', 'Malaisamy', 'Councillor',
   'Ward 36, Zone Tondiarpet', 'GCC Ward 36',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Malaisamy&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-037-councillor', 'ward-037', 'Dilli Babu', 'Councillor',
   'Ward 37, Zone Tondiarpet', 'GCC Ward 37',
   'INC', '#1a6fc4', 'https://api.dicebear.com/9.x/initials/svg?seed=Dilli%20Babu&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-038-councillor', 'ward-038', 'Ganesan Alias Nethaji Ganesan', 'Councillor',
   'Ward 38, Zone Tondiarpet', 'GCC Ward 38',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Ganesan%20Alias%20Nethaji%20Ganesan&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-039-councillor', 'ward-039', 'Devi Alias Devi Kathirasan', 'Councillor',
   'Ward 39, Zone Tondiarpet', 'GCC Ward 39',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Devi%20Alias%20Devi%20Kathirasan&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-040-councillor', 'ward-040', 'Kumari', 'Councillor',
   'Ward 40, Zone Tondiarpet', 'GCC Ward 40',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Kumari&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-041-councillor', 'ward-041', 'Vimala', 'Councillor',
   'Ward 41, Zone Tondiarpet', 'GCC Ward 41',
   'CPI(M)', '#b91c1c', 'https://api.dicebear.com/9.x/initials/svg?seed=Vimala&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-042-councillor', 'ward-042', 'Renuka', 'Councillor',
   'Ward 42, Zone Tondiarpet', 'GCC Ward 42',
   'CPI', '#dc2626', 'https://api.dicebear.com/9.x/initials/svg?seed=Renuka&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-043-councillor', 'ward-043', 'Pavithra', 'Councillor',
   'Ward 43, Zone Tondiarpet', 'GCC Ward 43',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Pavithra&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-044-councillor', 'ward-044', 'Surbajaya Das', 'Councillor',
   'Ward 44, Zone Tondiarpet', 'GCC Ward 44',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Surbajaya%20Das&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-045-councillor', 'ward-045', 'Gopinath', 'Councillor',
   'Ward 45, Zone Tondiarpet', 'GCC Ward 45',
   'VCK', '#1d4ed8', 'https://api.dicebear.com/9.x/initials/svg?seed=Gopinath&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-046-councillor', 'ward-046', 'Anandhi', 'Councillor',
   'Ward 46, Zone Tondiarpet', 'GCC Ward 46',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Anandhi&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-047-councillor', 'ward-047', 'Manimegalai', 'Councillor',
   'Ward 47, Zone Tondiarpet', 'GCC Ward 47',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Manimegalai&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-048-councillor', 'ward-048', 'Vijayalakshmi (a) Vijayalakshmi Vijayakumar', 'Councillor',
   'Ward 48, Zone Tondiarpet', 'GCC Ward 48',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Vijayalakshmi%20(a)%20Vijayalakshmi%20Vijayakumar&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-049-councillor', 'ward-049', 'Elango Alias Lllaya Aruna', 'Councillor',
   'Ward 49, Zone Royapuram', 'GCC Ward 49',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Elango%20Alias%20Lllaya%20Aruna&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-050-councillor', 'ward-050', 'Sureshkumar', 'Councillor',
   'Ward 50, Zone Royapuram', 'GCC Ward 50',
   'INC', '#1a6fc4', 'https://api.dicebear.com/9.x/initials/svg?seed=Sureshkumar&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-051-councillor', 'ward-051', 'Niranjana Jagadeesan', 'Councillor',
   'Ward 51, Zone Royapuram', 'GCC Ward 51',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Niranjana%20Jagadeesan&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-052-councillor', 'ward-052', 'Geetha Suresh', 'Councillor',
   'Ward 52, Zone Royapuram', 'GCC Ward 52',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Geetha%20Suresh&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-053-councillor', 'ward-053', 'Velakanni', 'Councillor',
   'Ward 53, Zone Royapuram', 'GCC Ward 53',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Velakanni&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-054-councillor', 'ward-054', 'Sriramulu', 'Councillor',
   'Ward 54, Zone Royapuram', 'GCC Ward 54',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Sriramulu&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-055-councillor', 'ward-055', 'Naveen.l', 'Councillor',
   'Ward 55, Zone Royapuram', 'GCC Ward 55',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Naveen.l&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-056-councillor', 'ward-056', 'Parimalam', 'Councillor',
   'Ward 56, Zone Royapuram', 'GCC Ward 56',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Parimalam&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-057-councillor', 'ward-057', 'Rajesh Jain', 'Councillor',
   'Ward 57, Zone Royapuram', 'GCC Ward 57',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Rajesh%20Jain&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-058-councillor', 'ward-058', 'Rajeswari', 'Councillor',
   'Ward 58, Zone Royapuram', 'GCC Ward 58',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Rajeswari&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-059-councillor', 'ward-059', 'Saraswathi', 'Councillor',
   'Ward 59, Zone Royapuram', 'GCC Ward 59',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Saraswathi&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-060-councillor', 'ward-060', 'Azath Z', 'Councillor',
   'Ward 60, Zone Royapuram', 'GCC Ward 60',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Azath%20Z&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-061-councillor', 'ward-061', 'Fathima Ahamath', 'Councillor',
   'Ward 61, Zone Royapuram', 'GCC Ward 61',
   'IUML', '#059669', 'https://api.dicebear.com/9.x/initials/svg?seed=Fathima%20Ahamath&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-062-councillor', 'ward-062', 'Jegadesan', 'Councillor',
   'Ward 62, Zone Royapuram', 'GCC Ward 62',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Jegadesan&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-063-councillor', 'ward-063', 'Rajasekaran', 'Councillor',
   'Ward 63, Zone Royapuram', 'GCC Ward 63',
   'INC', '#1a6fc4', 'https://api.dicebear.com/9.x/initials/svg?seed=Rajasekaran&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-064-councillor', 'ward-064', 'A.nagarajan', 'Councillor',
   'Ward 64, Zone Thiru-vi-ka-nagar', 'GCC Ward 64',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=A.nagarajan&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-065-councillor', 'ward-065', 'Saratha', 'Councillor',
   'Ward 65, Zone Thiru-vi-ka-nagar', 'GCC Ward 65',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Saratha&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-066-councillor', 'ward-066', 'Yogapriya', 'Councillor',
   'Ward 66, Zone Thiru-vi-ka-nagar', 'GCC Ward 66',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Yogapriya&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-067-councillor', 'ward-067', 'Dawood Bee', 'Councillor',
   'Ward 67, Zone Thiru-vi-ka-nagar', 'GCC Ward 67',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Dawood%20Bee&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-068-councillor', 'ward-068', 'Amudha', 'Councillor',
   'Ward 68, Zone Thiru-vi-ka-nagar', 'GCC Ward 68',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Amudha&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-069-councillor', 'ward-069', 'Saritha', 'Councillor',
   'Ward 69, Zone Thiru-vi-ka-nagar', 'GCC Ward 69',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Saritha&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-070-councillor', 'ward-070', 'Sridhani', 'Councillor',
   'Ward 70, Zone Thiru-vi-ka-nagar', 'GCC Ward 70',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Sridhani&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-071-councillor', 'ward-071', 'Punithavathi Alais Punithavathi Ethirajan', 'Councillor',
   'Ward 71, Zone Thiru-vi-ka-nagar', 'GCC Ward 71',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Punithavathi%20Alais%20Punithavathi%20Ethirajan&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-072-councillor', 'ward-072', 'Saravanan', 'Councillor',
   'Ward 72, Zone Thiru-vi-ka-nagar', 'GCC Ward 72',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Saravanan&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-073-councillor', 'ward-073', 'Ambedvalavan (a) Kumarasamy', 'Councillor',
   'Ward 73, Zone Thiru-vi-ka-nagar', 'GCC Ward 73',
   'VCK', '#1d4ed8', 'https://api.dicebear.com/9.x/initials/svg?seed=Ambedvalavan%20(a)%20Kumarasamy&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-074-councillor', 'ward-074', 'Priya.r', 'Councillor',
   'Ward 74, Zone Thiru-vi-ka-nagar', 'GCC Ward 74',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Priya.r&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-075-councillor', 'ward-075', 'Ramani', 'Councillor',
   'Ward 75, Zone Thiru-vi-ka-nagar', 'GCC Ward 75',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Ramani&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-076-councillor', 'ward-076', 'Tamilselvi', 'Councillor',
   'Ward 76, Zone Thiru-vi-ka-nagar', 'GCC Ward 76',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Tamilselvi&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-077-councillor', 'ward-077', 'Sumathi', 'Councillor',
   'Ward 77, Zone Thiru-vi-ka-nagar', 'GCC Ward 77',
   'INC', '#1a6fc4', 'https://api.dicebear.com/9.x/initials/svg?seed=Sumathi&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-078-councillor', 'ward-078', 'Velu', 'Councillor',
   'Ward 78, Zone Thiru-vi-ka-nagar', 'GCC Ward 78',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Velu&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-079-councillor', 'ward-079', 'Banupriya', 'Councillor',
   'Ward 79, Zone Ambattur', 'GCC Ward 79',
   'INC', '#1a6fc4', 'https://api.dicebear.com/9.x/initials/svg?seed=Banupriya&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-080-councillor', 'ward-080', 'Moorthi', 'Councillor',
   'Ward 80, Zone Ambattur', 'GCC Ward 80',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Moorthi&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-081-councillor', 'ward-081', 'Shantha Kumari', 'Councillor',
   'Ward 81, Zone Ambattur', 'GCC Ward 81',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Shantha%20Kumari&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-082-councillor', 'ward-082', 'Ramesh (a) Neelakandan', 'Councillor',
   'Ward 82, Zone Ambattur', 'GCC Ward 82',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Ramesh%20(a)%20Neelakandan&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-083-councillor', 'ward-083', 'Usha', 'Councillor',
   'Ward 83, Zone Ambattur', 'GCC Ward 83',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Usha&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-084-councillor', 'ward-084', 'John J', 'Councillor',
   'Ward 84, Zone Ambattur', 'GCC Ward 84',
   'AIADMK', '#006400', 'https://api.dicebear.com/9.x/initials/svg?seed=John%20J&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-085-councillor', 'ward-085', 'Porkodi', 'Councillor',
   'Ward 85, Zone Ambattur', 'GCC Ward 85',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Porkodi&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-086-councillor', 'ward-086', 'Kamal', 'Councillor',
   'Ward 86, Zone Ambattur', 'GCC Ward 86',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Kamal&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-087-councillor', 'ward-087', 'Poornima', 'Councillor',
   'Ward 87, Zone Ambattur', 'GCC Ward 87',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Poornima&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-088-councillor', 'ward-088', 'Nagavalli', 'Councillor',
   'Ward 88, Zone Ambattur', 'GCC Ward 88',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Nagavalli&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-089-councillor', 'ward-089', 'Sekar M.e', 'Councillor',
   'Ward 89, Zone Ambattur', 'GCC Ward 89',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Sekar%20M.e&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-090-councillor', 'ward-090', 'Rajagopal', 'Councillor',
   'Ward 90, Zone Ambattur', 'GCC Ward 90',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Rajagopal&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-091-councillor', 'ward-091', 'Malini', 'Councillor',
   'Ward 91, Zone Ambattur', 'GCC Ward 91',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Malini&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-092-councillor', 'ward-092', 'Thilakar', 'Councillor',
   'Ward 92, Zone Ambattur', 'GCC Ward 92',
   'Independent', '#64748b', 'https://api.dicebear.com/9.x/initials/svg?seed=Thilakar&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-093-councillor', 'ward-093', 'Uma', 'Councillor',
   'Ward 93, Zone Ambattur', 'GCC Ward 93',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Uma&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-094-councillor', 'ward-094', 'Jain Kubi', 'Councillor',
   'Ward 94, Zone Annanagar', 'GCC Ward 94',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Jain%20Kubi&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-095-councillor', 'ward-095', 'Sudha Dheenadayalan', 'Councillor',
   'Ward 95, Zone Annanagar', 'GCC Ward 95',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Sudha%20Dheenadayalan&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-096-councillor', 'ward-096', 'Dhanalakshmi', 'Councillor',
   'Ward 96, Zone Annanagar', 'GCC Ward 96',
   'INC', '#1a6fc4', 'https://api.dicebear.com/9.x/initials/svg?seed=Dhanalakshmi&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-097-councillor', 'ward-097', 'Latha (a) Latha Vasu', 'Councillor',
   'Ward 97, Zone Annanagar', 'GCC Ward 97',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Latha%20(a)%20Latha%20Vasu&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-098-councillor', 'ward-098', 'Priyadharshini', 'Councillor',
   'Ward 98, Zone Annanagar', 'GCC Ward 98',
   'CPI(M)', '#b91c1c', 'https://api.dicebear.com/9.x/initials/svg?seed=Priyadharshini&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-099-councillor', 'ward-099', 'Paridhi Lllamsurudhi', 'Councillor',
   'Ward 99, Zone Annanagar', 'GCC Ward 99',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Paridhi%20Lllamsurudhi&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-100-councillor', 'ward-100', 'Vasanthi Paramasivam', 'Councillor',
   'Ward 100, Zone Annanagar', 'GCC Ward 100',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Vasanthi%20Paramasivam&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-101-councillor', 'ward-101', 'Metilda Govindaraj', 'Councillor',
   'Ward 101, Zone Annanagar', 'GCC Ward 101',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Metilda%20Govindaraj&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-102-councillor', 'ward-102', 'Rani', 'Councillor',
   'Ward 102, Zone Annanagar', 'GCC Ward 102',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Rani&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-103-councillor', 'ward-103', 'Pushpalatha', 'Councillor',
   'Ward 103, Zone Annanagar', 'GCC Ward 103',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Pushpalatha&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-104-councillor', 'ward-104', 'Semmozhi', 'Councillor',
   'Ward 104, Zone Annanagar', 'GCC Ward 104',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Semmozhi&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-105-councillor', 'ward-105', 'Adhiyamaan', 'Councillor',
   'Ward 105, Zone Annanagar', 'GCC Ward 105',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Adhiyamaan&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-106-councillor', 'ward-106', 'Ramalingam', 'Councillor',
   'Ward 106, Zone Annanagar', 'GCC Ward 106',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Ramalingam&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-107-councillor', 'ward-107', 'Kiran Sharmili', 'Councillor',
   'Ward 107, Zone Annanagar', 'GCC Ward 107',
   'VCK', '#1d4ed8', 'https://api.dicebear.com/9.x/initials/svg?seed=Kiran%20Sharmili&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-108-councillor', 'ward-108', 'Sundarajan', 'Councillor',
   'Ward 108, Zone Annanagar', 'GCC Ward 108',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Sundarajan&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-109-councillor', 'ward-109', 'Suganya.a', 'Councillor',
   'Ward 109, Zone Teynampet', 'GCC Ward 109',
   'INC', '#1a6fc4', 'https://api.dicebear.com/9.x/initials/svg?seed=Suganya.a&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-110-councillor', 'ward-110', 'Citrarasu', 'Councillor',
   'Ward 110, Zone Teynampet', 'GCC Ward 110',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Citrarasu&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-111-councillor', 'ward-111', 'Nandhini', 'Councillor',
   'Ward 111, Zone Teynampet', 'GCC Ward 111',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Nandhini&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-112-councillor', 'ward-112', 'Elizabath Augastin', 'Councillor',
   'Ward 112, Zone Teynampet', 'GCC Ward 112',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Elizabath%20Augastin&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-113-councillor', 'ward-113', 'Prema Suresh', 'Councillor',
   'Ward 113, Zone Teynampet', 'GCC Ward 113',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Prema%20Suresh&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-114-councillor', 'ward-114', 'Madhan Mohan', 'Councillor',
   'Ward 114, Zone Teynampet', 'GCC Ward 114',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Madhan%20Mohan&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-115-councillor', 'ward-115', 'Eswari Venkatesan', 'Councillor',
   'Ward 115, Zone Teynampet', 'GCC Ward 115',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Eswari%20Venkatesan&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-116-councillor', 'ward-116', 'Kamaraj (a)dhanasekararpm', 'Councillor',
   'Ward 116, Zone Teynampet', 'GCC Ward 116',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Kamaraj%20(a)dhanasekararpm&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-117-councillor', 'ward-117', 'Thirumalai', 'Councillor',
   'Ward 117, Zone Teynampet', 'GCC Ward 117',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Thirumalai&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-118-councillor', 'ward-118', 'Malliga', 'Councillor',
   'Ward 118, Zone Teynampet', 'GCC Ward 118',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Malliga&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-119-councillor', 'ward-119', 'Kamala Chezhian', 'Councillor',
   'Ward 119, Zone Teynampet', 'GCC Ward 119',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Kamala%20Chezhian&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-120-councillor', 'ward-120', 'Mangai', 'Councillor',
   'Ward 120, Zone Teynampet', 'GCC Ward 120',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Mangai&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-121-councillor', 'ward-121', 'Mathivanan', 'Councillor',
   'Ward 121, Zone Teynampet', 'GCC Ward 121',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Mathivanan&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-122-councillor', 'ward-122', 'Sheeba', 'Councillor',
   'Ward 122, Zone Teynampet', 'GCC Ward 122',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Sheeba&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-123-councillor', 'ward-123', 'Sara Swath I', 'Councillor',
   'Ward 123, Zone Teynampet', 'GCC Ward 123',
   'CPI(M)', '#b91c1c', 'https://api.dicebear.com/9.x/initials/svg?seed=Sara%20Swath%20I&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-124-councillor', 'ward-124', 'Vimala', 'Councillor',
   'Ward 124, Zone Teynampet', 'GCC Ward 124',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Vimala&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-125-councillor', 'ward-125', 'Revathi', 'Councillor',
   'Ward 125, Zone Teynampet', 'GCC Ward 125',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Revathi&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-126-councillor', 'ward-126', 'Amirthavarshini', 'Councillor',
   'Ward 126, Zone Teynampet', 'GCC Ward 126',
   'INC', '#1a6fc4', 'https://api.dicebear.com/9.x/initials/svg?seed=Amirthavarshini&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-127-councillor', 'ward-127', 'Logu', 'Councillor',
   'Ward 127, Zone Kodambakkam', 'GCC Ward 127',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Logu&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-128-councillor', 'ward-128', 'Stella Jasmine Rathna', 'Councillor',
   'Ward 128, Zone Kodambakkam', 'GCC Ward 128',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Stella%20Jasmine%20Rathna&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-129-councillor', 'ward-129', 'Ravishankar (a) Rasa', 'Councillor',
   'Ward 129, Zone Kodambakkam', 'GCC Ward 129',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Ravishankar%20(a)%20Rasa&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-130-councillor', 'ward-130', 'Baskar', 'Councillor',
   'Ward 130, Zone Kodambakkam', 'GCC Ward 130',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Baskar&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-131-councillor', 'ward-131', 'Gomathi', 'Councillor',
   'Ward 131, Zone Kodambakkam', 'GCC Ward 131',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Gomathi&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-132-councillor', 'ward-132', 'Karthika', 'Councillor',
   'Ward 132, Zone Kodambakkam', 'GCC Ward 132',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Karthika&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-133-councillor', 'ward-133', 'Elumalai', 'Councillor',
   'Ward 133, Zone Kodambakkam', 'GCC Ward 133',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Elumalai&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-134-councillor', 'ward-134', 'Uma Anandhan', 'Councillor',
   'Ward 134, Zone Kodambakkam', 'GCC Ward 134',
   'BJP', '#ff6600', 'https://api.dicebear.com/9.x/initials/svg?seed=Uma%20Anandhan&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-135-councillor', 'ward-135', 'Shanthi (a) Azhini', 'Councillor',
   'Ward 135, Zone Kodambakkam', 'GCC Ward 135',
   'VCK', '#1d4ed8', 'https://api.dicebear.com/9.x/initials/svg?seed=Shanthi%20(a)%20Azhini&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-136-councillor', 'ward-136', 'Nilavarasi', 'Councillor',
   'Ward 136, Zone Kodambakkam', 'GCC Ward 136',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Nilavarasi&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-137-councillor', 'ward-137', 'Dhanasekaran', 'Councillor',
   'Ward 137, Zone Kodambakkam', 'GCC Ward 137',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Dhanasekaran&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-138-councillor', 'ward-138', 'Kannan', 'Councillor',
   'Ward 138, Zone Kodambakkam', 'GCC Ward 138',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Kannan&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-139-councillor', 'ward-139', 'Subramani', 'Councillor',
   'Ward 139, Zone Kodambakkam', 'GCC Ward 139',
   'MDMK', '#991b1b', 'https://api.dicebear.com/9.x/initials/svg?seed=Subramani&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-140-councillor', 'ward-140', 'Sridharan', 'Councillor',
   'Ward 140, Zone Kodambakkam', 'GCC Ward 140',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Sridharan&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-141-councillor', 'ward-141', 'Raja Anbazhagan', 'Councillor',
   'Ward 141, Zone Kodambakkam', 'GCC Ward 141',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Raja%20Anbazhagan&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-142-councillor', 'ward-142', 'Krishnamoorthy', 'Councillor',
   'Ward 142, Zone Kodambakkam', 'GCC Ward 142',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Krishnamoorthy&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-143-councillor', 'ward-143', 'Rajan', 'Councillor',
   'Ward 143, Zone Valasaravakkam', 'GCC Ward 143',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Rajan&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-144-councillor', 'ward-144', 'Stalin', 'Councillor',
   'Ward 144, Zone Valasaravakkam', 'GCC Ward 144',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Stalin&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-145-councillor', 'ward-145', 'Sathya Nathan', 'Councillor',
   'Ward 145, Zone Valasaravakkam', 'GCC Ward 145',
   'AIADMK', '#006400', 'https://api.dicebear.com/9.x/initials/svg?seed=Sathya%20Nathan&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-146-councillor', 'ward-146', 'Alapakkam K Shanmugam', 'Councillor',
   'Ward 146, Zone Valasaravakkam', 'GCC Ward 146',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Alapakkam%20K%20Shanmugam&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-147-councillor', 'ward-147', 'Ramani Madhavan', 'Councillor',
   'Ward 147, Zone Valasaravakkam', 'GCC Ward 147',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Ramani%20Madhavan&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-148-councillor', 'ward-148', 'Giridharan', 'Councillor',
   'Ward 148, Zone Valasaravakkam', 'GCC Ward 148',
   'AMMK', '#7c3aed', 'https://api.dicebear.com/9.x/initials/svg?seed=Giridharan&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-149-councillor', 'ward-149', 'Selvi Ramesh', 'Councillor',
   'Ward 149, Zone Valasaravakkam', 'GCC Ward 149',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Selvi%20Ramesh&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-150-councillor', 'ward-150', 'Hemalatha', 'Councillor',
   'Ward 150, Zone Valasaravakkam', 'GCC Ward 150',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Hemalatha&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-151-councillor', 'ward-151', 'Shankar Ganesh', 'Councillor',
   'Ward 151, Zone Valasaravakkam', 'GCC Ward 151',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Shankar%20Ganesh&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-152-councillor', 'ward-152', 'Bharathi', 'Councillor',
   'Ward 152, Zone Valasaravakkam', 'GCC Ward 152',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Bharathi&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-153-councillor', 'ward-153', 'Shanthi', 'Councillor',
   'Ward 153, Zone Valasaravakkam', 'GCC Ward 153',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Shanthi&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-154-councillor', 'ward-154', 'Selvakumar', 'Councillor',
   'Ward 154, Zone Valasaravakkam', 'GCC Ward 154',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Selvakumar&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-155-councillor', 'ward-155', 'Raji', 'Councillor',
   'Ward 155, Zone Valasaravakkam', 'GCC Ward 155',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Raji&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-156-councillor', 'ward-156', 'Selvendran.j', 'Councillor',
   'Ward 156, Zone Alandur', 'GCC Ward 156',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Selvendran.j&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-157-councillor', 'ward-157', 'Usharani', 'Councillor',
   'Ward 157, Zone Alandur', 'GCC Ward 157',
   'AIADMK', '#006400', 'https://api.dicebear.com/9.x/initials/svg?seed=Usharani&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-158-councillor', 'ward-158', 'Bharathi Ko', 'Councillor',
   'Ward 158, Zone Alandur', 'GCC Ward 158',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Bharathi%20Ko&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-159-councillor', 'ward-159', 'Amudha Priya.s', 'Councillor',
   'Ward 159, Zone Alandur', 'GCC Ward 159',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Amudha%20Priya.s&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-160-councillor', 'ward-160', 'Brindha', 'Councillor',
   'Ward 160, Zone Alandur', 'GCC Ward 160',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Brindha&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-161-councillor', 'ward-161', 'Renuka', 'Councillor',
   'Ward 161, Zone Alandur', 'GCC Ward 161',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Renuka&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-162-councillor', 'ward-162', 'Solomon', 'Councillor',
   'Ward 162, Zone Alandur', 'GCC Ward 162',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Solomon&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-163-councillor', 'ward-163', 'Poongkodi', 'Councillor',
   'Ward 163, Zone Alandur', 'GCC Ward 163',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Poongkodi&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-164-councillor', 'ward-164', 'Devi.j', 'Councillor',
   'Ward 164, Zone Alandur', 'GCC Ward 164',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Devi.j&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-165-councillor', 'ward-165', 'Nanjil V Eswara Prasad', 'Councillor',
   'Ward 165, Zone Alandur', 'GCC Ward 165',
   'INC', '#1a6fc4', 'https://api.dicebear.com/9.x/initials/svg?seed=Nanjil%20V%20Eswara%20Prasad&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-166-councillor', 'ward-166', 'Chandran', 'Councillor',
   'Ward 166, Zone Alandur', 'GCC Ward 166',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Chandran&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-167-councillor', 'ward-167', 'Durga Devi', 'Councillor',
   'Ward 167, Zone Alandur', 'GCC Ward 167',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Durga%20Devi&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-168-councillor', 'ward-168', 'Mohankumar', 'Councillor',
   'Ward 168, Zone Perungudi', 'GCC Ward 168',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Mohankumar&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-169-councillor', 'ward-169', 'Mahesh Kumar', 'Councillor',
   'Ward 169, Zone Perungudi', 'GCC Ward 169',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Mahesh%20Kumar&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-170-councillor', 'ward-170', 'Kathir Murugan', 'Councillor',
   'Ward 170, Zone Adyar', 'GCC Ward 170',
   'AIADMK', '#006400', 'https://api.dicebear.com/9.x/initials/svg?seed=Kathir%20Murugan&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-171-councillor', 'ward-171', 'Geetha', 'Councillor',
   'Ward 171, Zone Adyar', 'GCC Ward 171',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Geetha&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-172-councillor', 'ward-172', 'Durairaj', 'Councillor',
   'Ward 172, Zone Adyar', 'GCC Ward 172',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Durairaj&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-173-councillor', 'ward-173', 'Subhashini', 'Councillor',
   'Ward 173, Zone Adyar', 'GCC Ward 173',
   'INC', '#1a6fc4', 'https://api.dicebear.com/9.x/initials/svg?seed=Subhashini&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-174-councillor', 'ward-174', 'Radhika', 'Councillor',
   'Ward 174, Zone Adyar', 'GCC Ward 174',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Radhika&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-175-councillor', 'ward-175', 'Mageshwari Murugavel', 'Councillor',
   'Ward 175, Zone Adyar', 'GCC Ward 175',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Mageshwari%20Murugavel&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-176-councillor', 'ward-176', 'Anandham', 'Councillor',
   'Ward 176, Zone Adyar', 'GCC Ward 176',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Anandham&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-177-councillor', 'ward-177', 'Manimaran', 'Councillor',
   'Ward 177, Zone Adyar', 'GCC Ward 177',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Manimaran&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-178-councillor', 'ward-178', 'Baskaran', 'Councillor',
   'Ward 178, Zone Adyar', 'GCC Ward 178',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Baskaran&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-179-councillor', 'ward-179', 'Kayalvizhi', 'Councillor',
   'Ward 179, Zone Adyar', 'GCC Ward 179',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Kayalvizhi&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-180-councillor', 'ward-180', 'Vishalakshi', 'Councillor',
   'Ward 180, Zone Adyar', 'GCC Ward 180',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Vishalakshi&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-181-councillor', 'ward-181', 'Viswanathan', 'Councillor',
   'Ward 181, Zone Adyar', 'GCC Ward 181',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Viswanathan&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-182-councillor', 'ward-182', 'Sathishkumar Kpk', 'Councillor',
   'Ward 182, Zone Adyar', 'GCC Ward 182',
   'AIADMK', '#006400', 'https://api.dicebear.com/9.x/initials/svg?seed=Sathishkumar%20Kpk&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-183-councillor', 'ward-183', 'Tamizharasi Somu', 'Councillor',
   'Ward 183, Zone Perungudi', 'GCC Ward 183',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Tamizharasi%20Somu&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-184-councillor', 'ward-184', 'Ravichandran', 'Councillor',
   'Ward 184, Zone Perungudi', 'GCC Ward 184',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Ravichandran&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-185-councillor', 'ward-185', 'Sharmila Devi', 'Councillor',
   'Ward 185, Zone Perungudi', 'GCC Ward 185',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Sharmila%20Devi&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-186-councillor', 'ward-186', 'Manikandan', 'Councillor',
   'Ward 186, Zone Perungudi', 'GCC Ward 186',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Manikandan&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-187-councillor', 'ward-187', 'Sherli Thomas', 'Councillor',
   'Ward 187, Zone Perungudi', 'GCC Ward 187',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Sherli%20Thomas&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-188-councillor', 'ward-188', 'Shamina', 'Councillor',
   'Ward 188, Zone Perungudi', 'GCC Ward 188',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Shamina&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-189-councillor', 'ward-189', 'Babu', 'Councillor',
   'Ward 189, Zone Perungudi', 'GCC Ward 189',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Babu&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-190-councillor', 'ward-190', 'Sivaprakasam', 'Councillor',
   'Ward 190, Zone Perungudi', 'GCC Ward 190',
   'AIADMK', '#006400', 'https://api.dicebear.com/9.x/initials/svg?seed=Sivaprakasam&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-191-councillor', 'ward-191', 'Lakshmi', 'Councillor',
   'Ward 191, Zone Perungudi', 'GCC Ward 191',
   'AIADMK', '#006400', 'https://api.dicebear.com/9.x/initials/svg?seed=Lakshmi&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-192-councillor', 'ward-192', 'Mathiazhagan', 'Councillor',
   'Ward 192, Zone Sozhinganallur', 'GCC Ward 192',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Mathiazhagan&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-193-councillor', 'ward-193', 'Govindhaswamy', 'Councillor',
   'Ward 193, Zone Sozhinganallur', 'GCC Ward 193',
   'AIADMK', '#006400', 'https://api.dicebear.com/9.x/initials/svg?seed=Govindhaswamy&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-194-councillor', 'ward-194', 'Vimala Kama', 'Councillor',
   'Ward 194, Zone Sozhinganallur', 'GCC Ward 194',
   'Independent', '#64748b', 'https://api.dicebear.com/9.x/initials/svg?seed=Vimala%20Kama&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-195-councillor', 'ward-195', 'Ekambaram', 'Councillor',
   'Ward 195, Zone Sozhinganallur', 'GCC Ward 195',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Ekambaram&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-196-councillor', 'ward-196', 'Ashwini', 'Councillor',
   'Ward 196, Zone Sozhinganallur', 'GCC Ward 196',
   'AIADMK', '#006400', 'https://api.dicebear.com/9.x/initials/svg?seed=Ashwini&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-197-councillor', 'ward-197', 'Menaka', 'Councillor',
   'Ward 197, Zone Sozhinganallur', 'GCC Ward 197',
   'AIADMK', '#006400', 'https://api.dicebear.com/9.x/initials/svg?seed=Menaka&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-198-councillor', 'ward-198', 'Sundaram', 'Councillor',
   'Ward 198, Zone Sozhinganallur', 'GCC Ward 198',
   'Independent', '#64748b', 'https://api.dicebear.com/9.x/initials/svg?seed=Sundaram&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-199-councillor', 'ward-199', 'Shankar', 'Councillor',
   'Ward 199, Zone Sozhinganallur', 'GCC Ward 199',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Shankar&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone'),
  ('rep-ward-200-councillor', 'ward-200', 'Murugesan', 'Councillor',
   'Ward 200, Zone Sozhinganallur', 'GCC Ward 200',
   'DMK', '#e3000f', 'https://api.dicebear.com/9.x/initials/svg?seed=Murugesan&backgroundColor=e2e8f0&fontFamily=Arial&fontSize=40',
   'commr.gcc@gmail.com', '1913', 'Mon-Sat, 10:00 AM – 5:00 PM', 'phone')
on conflict (id) do update set
  ward_id = excluded.ward_id,
  name = excluded.name,
  role = excluded.role,
  area = excluded.area,
  constituency = excluded.constituency,
  party = excluded.party,
  party_color = excluded.party_color,
  photo_url = excluded.photo_url,
  email = excluded.email,
  helpline = excluded.helpline,
  office_hours = excluded.office_hours,
  preferred_channel = excluded.preferred_channel,
  updated_at = now();
